services:
  frontend:
    build:
      context: ./letterboxle-frontend
    container_name: letterboxle-frontend
    restart: unless-stopped
    networks:
      - npm

networks:
  npm:
    external: true

